---
title: "Study 3 Analysis"
author: "Dennis W.H. Teo"
output: 
  html_document:
    theme: darkly
    toc: yes
    toc_depth: 3
    toc_float: true
    highlight: tango
    df_print: paged
    fig_caption: false
    code_fold: hide
fontsize: 18pt
---

```{r echo=FALSE, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(message = FALSE, warning = FALSE, message = FALSE)

```

```{r}

library(readr)

attobo3 <- read_csv("attobo3_clean.csv")

library(dthelper)
library(ggplot2)
library(tidyverse)
library(foreign)
library(nnet)

```

# Descriptive Stats

## Sample Breakdown

Total number of participants: `r nrow(attobo3)`

## Histograms of Collected Measures

```{r }

attobo3.demo <- attobo3 %>%
  select(Gender, Race, Age, Education)

attobo3.advice <- attobo3 %>%
  select(StratAcad, EffortAcad, StratSports, EffortSports,
         StratParent, EffortParent, StratDiet, EffortDiet,
         StratTeam, EffortTeam, StratSales, EffortSales,
         StratRelation, EffortRelation, Order)

attobo3.attribution <- attobo3 %>%
  select(Effort.Locus.External, Strat.Locus.External,
         Effort.Variable, Strat.Variable,
         Effort.Others.Uncon, Strat.Others.Uncon,
         Effort.Personal.Uncon, Strat.Personal.Uncon)

ggplot(data = gather(attobo3.advice, factor_key = TRUE), aes(x = factor(value))) +
  geom_bar() + 
  facet_wrap(~ key,scales = "free", as.table = TRUE, nrow = 3) + xlab("") + 
  theme_bw()

ggplot(data = gather(attobo3.attribution, factor_key = TRUE), aes(x = factor(value))) +
  geom_bar() + 
  facet_wrap(~ key,scales = "free", as.table = TRUE, nrow = 3) + xlab("") + 
  theme_bw()

ggplot(data = gather(attobo3.demo, factor_key = TRUE), aes(x = factor(value))) +
  geom_bar() + 
  facet_wrap(~ key,scales = "free", as.table = TRUE, nrow = 3) + xlab("") + 
  theme_bw()


```

# Main Analysis

## Academic Scenario Analysis

```{r }

## Preparing Data
acad.long <- gather.keep(attobo3, keep = c("...1"), 
                            var.to.gather = c("StratAcad", "EffortAcad"),
                            key = "attribution",
                            value = "advice"
                            )

acad.long$advice <- as.numeric(factor(acad.long$advice, 
                                levels = c( "Method", "BF","Default", "Give up")
                                ))
acad.long$advice <- acad.long$advice - 1

acad.long$attribution <- factor(acad.long$attribution, 
                                levels = c( "EffortAcad", "StratAcad"),
                                labels = c("effort", "strategy")
                                )


```

```{r eval = F}

set.seed(100)

df <- data.frame(choices = acad.long$advice, attribution = acad.long$attribution)

df$attribution <- factor(df$attribution )

N <- nrow(df)
nSims <- 5000

boot.method.eff <- c()
boot.method.strat <- c()
boot.bf.eff <- c()
boot.bf.strat <- c()
boot.default.eff <- c()
boot.default.strat <- c()
boot.giveup.eff <- c()
boot.giveup.strat <- c()


for (i in 1:nSims){
  
  df.boot <- df[resample(1:(N), N), ]

  test.boot <- multinom(choices ~ attribution, data = df.boot, trace = F)
  summary(test.boot)
  
  newpred <- data.frame(attribution = c("effort","strategy"))
  pred <- predict(test.boot, newdata = newpred, "prob")
  
  
  boot.method.eff[i] <- pred[1,1]
  boot.method.strat[i] <- pred[2,1]
  boot.bf.eff[i] <- pred[1,2]
  boot.bf.strat[i] <- pred[2,2]
  boot.default.eff[i] <- pred[1,3]
  boot.default.strat[i] <- pred[2,3]
  boot.giveup.eff[i] <- pred[1,4]
  boot.giveup.strat[i] <- pred[2,4]

}

acad.boot <- data.frame(
  boot.method.eff = boot.method.eff,
  boot.method.strat = boot.method.strat,
  boot.bf.eff = boot.bf.eff,
  boot.bf.strat = boot.bf.strat,
  boot.default.eff = boot.default.eff,
  boot.defaule.strat = boot.default.strat,
  boot.giveup.eff = boot.giveup.eff,
  boot.giveup.strat = boot.giveup.strat
)

acad.summary <- data.frame(
  attribution = rep( c("Effort", "Strategy"), 4 ),
  advice = rep( c("Method",  "Bruteforce", "Default", "Give Up"), each = 2 ),
  mean_coef = c(mean(boot.method.eff),mean(boot.method.strat),
                mean(boot.bf.eff),mean(boot.bf.strat),
                mean(boot.default.eff),mean(boot.default.strat),
                mean(boot.giveup.eff),mean(boot.giveup.strat)
                ),
  lower_coef = c(quantile(boot.method.eff, .025),
                 quantile(boot.method.strat,.025),
                 quantile(boot.bf.eff, .025),
                 quantile(boot.bf.strat,.025),
                 quantile(boot.default.eff, .025),
                 quantile(boot.default.strat,.025),
                 quantile(boot.giveup.eff, .025),
                 quantile(boot.giveup.strat,.025)
                 ),
  upper_coef = c(quantile(boot.method.eff, .975),
                 quantile(boot.method.strat,.975),
                 quantile(boot.bf.eff, .975),
                 quantile(boot.bf.strat,.975),
                 quantile(boot.default.eff, .975),
                 quantile(boot.default.strat,.975),
                 quantile(boot.giveup.eff, .975),
                 quantile(boot.giveup.strat,.975)
                 )
)

```

```{r cache = T}
acad.summary
```




## Dieting Scenario Analysis


```{r }

## Preparing Data
diet.long <- gather.keep(attobo3, keep = c("...1"), 
                            var.to.gather = c("StratDiet", "EffortDiet"),
                            key = "attribution",
                            value = "advice"
                            )

diet.long$advice <- as.numeric(factor(diet.long$advice, 
                                levels = c( "Method", "BF","Default", "Give up")
                                ))
diet.long$advice <- diet.long$advice - 1

diet.long$attribution <- factor(diet.long$attribution, 
                                levels = c( "EffortDiet", "StratDiet"),
                                labels = c("effort", "strategy")
                                )


```


```{r eval = F}

set.seed(100)

df <- data.frame(choices = diet.long$advice, attribution = diet.long$attribution)

df$attribution <- factor(df$attribution )

N <- nrow(df)
nSims <- 5000

boot.method.eff <- c()
boot.method.strat <- c()
boot.bf.eff <- c()
boot.bf.strat <- c()
boot.default.eff <- c()
boot.default.strat <- c()
boot.giveup.eff <- c()
boot.giveup.strat <- c()


for (i in 1:nSims){
  
  df.boot <- df[resample(1:(N), N), ]

  test.boot <- multinom(choices ~ attribution, data = df.boot, trace = F)
  summary(test.boot)
  
  newpred <- data.frame(attribution = c("effort","strategy"))
  pred <- predict(test.boot, newdata = newpred, "prob")
  
  
  boot.method.eff[i] <- pred[1,1]
  boot.method.strat[i] <- pred[2,1]
  boot.bf.eff[i] <- pred[1,2]
  boot.bf.strat[i] <- pred[2,2]
  boot.default.eff[i] <- pred[1,3]
  boot.default.strat[i] <- pred[2,3]
  boot.giveup.eff[i] <- pred[1,4]
  boot.giveup.strat[i] <- pred[2,4]

}

diet.boot <- data.frame(
  boot.method.eff = boot.method.eff,
  boot.method.strat = boot.method.strat,
  boot.bf.eff = boot.bf.eff,
  boot.bf.strat = boot.bf.strat,
  boot.default.eff = boot.default.eff,
  boot.defaule.strat = boot.default.strat,
  boot.giveup.eff = boot.giveup.eff,
  boot.giveup.strat = boot.giveup.strat
)

diet.summary <- data.frame(
  attribution = rep( c("Effort", "Strategy"), 4 ),
  advice = rep( c("Method",  "Bruteforce", "Default", "Give Up"), each = 2 ),
  mean_coef = c(mean(boot.method.eff),mean(boot.method.strat),
                mean(boot.bf.eff),mean(boot.bf.strat),
                mean(boot.default.eff),mean(boot.default.strat),
                mean(boot.giveup.eff),mean(boot.giveup.strat)
                ),
  lower_coef = c(quantile(boot.method.eff, .025),
                 quantile(boot.method.strat,.025),
                 quantile(boot.bf.eff, .025),
                 quantile(boot.bf.strat,.025),
                 quantile(boot.default.eff, .025),
                 quantile(boot.default.strat,.025),
                 quantile(boot.giveup.eff, .025),
                 quantile(boot.giveup.strat,.025)
                 ),
  upper_coef = c(quantile(boot.method.eff, .975),
                 quantile(boot.method.strat,.975),
                 quantile(boot.bf.eff, .975),
                 quantile(boot.bf.strat,.975),
                 quantile(boot.default.eff, .975),
                 quantile(boot.default.strat,.975),
                 quantile(boot.giveup.eff, .975),
                 quantile(boot.giveup.strat,.975)
                 )
)

```

```{r cache = T}
diet.summary
```


## Parenting Scenario Analysis

```{r }
## Preparing Data
parent.long <- gather.keep(attobo3, keep = c("...1"), 
                            var.to.gather = c("StratParent", "EffortParent"),
                            key = "attribution",
                            value = "advice"
                            )

parent.long$advice <- as.numeric(factor(parent.long$advice, 
                                levels = c( "Method", "BF","Default", "Give up")
                                ))
parent.long$advice <- parent.long$advice - 1

parent.long$attribution <- factor(parent.long$attribution, 
                                levels = c( "EffortParent", "StratParent"),
                                labels = c("effort", "strategy")
                                )


```

```{r eval = F}

set.seed(100)

df <- data.frame(choices = parent.long$advice, attribution = parent.long$attribution)

df$attribution <- factor(df$attribution )

N <- nrow(df)
nSims <- 5000

boot.method.eff <- c()
boot.method.strat <- c()
boot.bf.eff <- c()
boot.bf.strat <- c()
boot.default.eff <- c()
boot.default.strat <- c()
boot.giveup.eff <- c()
boot.giveup.strat <- c()


for (i in 1:nSims){
  
  df.boot <- df[resample(1:(N), N), ]

  test.boot <- multinom(choices ~ attribution, data = df.boot, trace = F)
  summary(test.boot)
  
  newpred <- data.frame(attribution = c("effort","strategy"))
  pred <- predict(test.boot, newdata = newpred, "prob")
  
  
  boot.method.eff[i] <- pred[1,1]
  boot.method.strat[i] <- pred[2,1]
  boot.bf.eff[i] <- pred[1,2]
  boot.bf.strat[i] <- pred[2,2]
  boot.default.eff[i] <- pred[1,3]
  boot.default.strat[i] <- pred[2,3]
  boot.giveup.eff[i] <- pred[1,4]
  boot.giveup.strat[i] <- pred[2,4]

}

parent.boot <- data.frame(
  boot.method.eff = boot.method.eff,
  boot.method.strat = boot.method.strat,
  boot.bf.eff = boot.bf.eff,
  boot.bf.strat = boot.bf.strat,
  boot.default.eff = boot.default.eff,
  boot.defaule.strat = boot.default.strat,
  boot.giveup.eff = boot.giveup.eff,
  boot.giveup.strat = boot.giveup.strat
)

parent.summary <- data.frame(
  attribution = rep( c("Effort", "Strategy"), 4 ),
  advice = rep( c("Method",  "Bruteforce", "Default", "Give Up"), each = 2 ),
  mean_coef = c(mean(boot.method.eff),mean(boot.method.strat),
                mean(boot.bf.eff),mean(boot.bf.strat),
                mean(boot.default.eff),mean(boot.default.strat),
                mean(boot.giveup.eff),mean(boot.giveup.strat)
                ),
  lower_coef = c(quantile(boot.method.eff, .025),
                 quantile(boot.method.strat,.025),
                 quantile(boot.bf.eff, .025),
                 quantile(boot.bf.strat,.025),
                 quantile(boot.default.eff, .025),
                 quantile(boot.default.strat,.025),
                 quantile(boot.giveup.eff, .025),
                 quantile(boot.giveup.strat,.025)
                 ),
  upper_coef = c(quantile(boot.method.eff, .975),
                 quantile(boot.method.strat,.975),
                 quantile(boot.bf.eff, .975),
                 quantile(boot.bf.strat,.975),
                 quantile(boot.default.eff, .975),
                 quantile(boot.default.strat,.975),
                 quantile(boot.giveup.eff, .975),
                 quantile(boot.giveup.strat,.975)
                 )
)

```

```{r cache = T}
parent.summary
```


## Relationship Scenario Analysis

```{r }
## Preparing Data
relation.long <- gather.keep(attobo3, keep = c("...1"), 
                            var.to.gather = c("StratRelation", "EffortRelation"),
                            key = "attribution",
                            value = "advice"
                            )

relation.long$advice <- as.numeric(factor(relation.long$advice, 
                                levels = c( "Method", "BF","Default", "Give up")
                                ))
relation.long$advice <- relation.long$advice - 1

relation.long$attribution <- factor(relation.long$attribution, 
                                levels = c( "EffortRelation", "StratRelation"),
                                labels = c("effort", "strategy")
                                )


```

```{r eval = F}

set.seed(100)

df <- data.frame(choices = relation.long$advice, attribution = relation.long$attribution)

df$attribution <- factor(df$attribution )

N <- nrow(df)
nSims <- 5000

boot.method.eff <- c()
boot.method.strat <- c()
boot.bf.eff <- c()
boot.bf.strat <- c()
boot.default.eff <- c()
boot.default.strat <- c()
boot.giveup.eff <- c()
boot.giveup.strat <- c()


for (i in 1:nSims){
  
  df.boot <- df[resample(1:(N), N), ]

  test.boot <- multinom(choices ~ attribution, data = df.boot, trace = F)
  summary(test.boot)
  
  newpred <- data.frame(attribution = c("effort","strategy"))
  pred <- predict(test.boot, newdata = newpred, "prob")
  
  
  boot.method.eff[i] <- pred[1,1]
  boot.method.strat[i] <- pred[2,1]
  boot.bf.eff[i] <- pred[1,2]
  boot.bf.strat[i] <- pred[2,2]
  boot.default.eff[i] <- pred[1,3]
  boot.default.strat[i] <- pred[2,3]
  boot.giveup.eff[i] <- pred[1,4]
  boot.giveup.strat[i] <- pred[2,4]

}

relation.boot <- data.frame(
  boot.method.eff = boot.method.eff,
  boot.method.strat = boot.method.strat,
  boot.bf.eff = boot.bf.eff,
  boot.bf.strat = boot.bf.strat,
  boot.default.eff = boot.default.eff,
  boot.defaule.strat = boot.default.strat,
  boot.giveup.eff = boot.giveup.eff,
  boot.giveup.strat = boot.giveup.strat
)

relation.summary <- data.frame(
  attribution = rep( c("Effort", "Strategy"), 4 ),
  advice = rep( c("Method",  "Bruteforce", "Default", "Give Up"), each = 2 ),
  mean_coef = c(mean(boot.method.eff),mean(boot.method.strat),
                mean(boot.bf.eff),mean(boot.bf.strat),
                mean(boot.default.eff),mean(boot.default.strat),
                mean(boot.giveup.eff),mean(boot.giveup.strat)
                ),
  lower_coef = c(quantile(boot.method.eff, .025),
                 quantile(boot.method.strat,.025),
                 quantile(boot.bf.eff, .025),
                 quantile(boot.bf.strat,.025),
                 quantile(boot.default.eff, .025),
                 quantile(boot.default.strat,.025),
                 quantile(boot.giveup.eff, .025),
                 quantile(boot.giveup.strat,.025)
                 ),
  upper_coef = c(quantile(boot.method.eff, .975),
                 quantile(boot.method.strat,.975),
                 quantile(boot.bf.eff, .975),
                 quantile(boot.bf.strat,.975),
                 quantile(boot.default.eff, .975),
                 quantile(boot.default.strat,.975),
                 quantile(boot.giveup.eff, .975),
                 quantile(boot.giveup.strat,.975)
                 )
)

```

```{r cache = T}
relation.summary
```

## Sales Scenario Analysis

```{r }
## Preparing Data
sales.long <- gather.keep(attobo3, keep = c("...1"), 
                            var.to.gather = c("StratSales", "EffortSales"),
                            key = "attribution",
                            value = "advice"
                            )

sales.long$advice <- as.numeric(factor(sales.long$advice, 
                                levels = c( "Method", "BF","Default", "Give up")
                                ))
sales.long$advice <- sales.long$advice - 1

sales.long$attribution <- factor(sales.long$attribution, 
                                levels = c( "EffortSales", "StratSales"),
                                labels = c("effort", "strategy")
                                )


```

```{r eval = F}

set.seed(100)

df <- data.frame(choices = sales.long$advice, attribution = sales.long$attribution)

df$attribution <- factor(df$attribution )

N <- nrow(df)
nSims <- 5000

boot.method.eff <- c()
boot.method.strat <- c()
boot.bf.eff <- c()
boot.bf.strat <- c()
boot.default.eff <- c()
boot.default.strat <- c()
boot.giveup.eff <- c()
boot.giveup.strat <- c()


for (i in 1:nSims){
  
  df.boot <- df[resample(1:(N), N), ]

  test.boot <- multinom(choices ~ attribution, data = df.boot, trace = F)
  summary(test.boot)
  
  newpred <- data.frame(attribution = c("effort","strategy"))
  pred <- predict(test.boot, newdata = newpred, "prob")
  
  
  boot.method.eff[i] <- pred[1,1]
  boot.method.strat[i] <- pred[2,1]
  boot.bf.eff[i] <- pred[1,2]
  boot.bf.strat[i] <- pred[2,2]
  boot.default.eff[i] <- pred[1,3]
  boot.default.strat[i] <- pred[2,3]
  boot.giveup.eff[i] <- pred[1,4]
  boot.giveup.strat[i] <- pred[2,4]

}

sales.boot <- data.frame(
  boot.method.eff = boot.method.eff,
  boot.method.strat = boot.method.strat,
  boot.bf.eff = boot.bf.eff,
  boot.bf.strat = boot.bf.strat,
  boot.default.eff = boot.default.eff,
  boot.defaule.strat = boot.default.strat,
  boot.giveup.eff = boot.giveup.eff,
  boot.giveup.strat = boot.giveup.strat
)

sales.summary <- data.frame(
  attribution = rep( c("Effort", "Strategy"), 4 ),
  advice = rep( c("Method",  "Bruteforce", "Default", "Give Up"), each = 2 ),
  mean_coef = c(mean(boot.method.eff),mean(boot.method.strat),
                mean(boot.bf.eff),mean(boot.bf.strat),
                mean(boot.default.eff),mean(boot.default.strat),
                mean(boot.giveup.eff),mean(boot.giveup.strat)
                ),
  lower_coef = c(quantile(boot.method.eff, .025),
                 quantile(boot.method.strat,.025),
                 quantile(boot.bf.eff, .025),
                 quantile(boot.bf.strat,.025),
                 quantile(boot.default.eff, .025),
                 quantile(boot.default.strat,.025),
                 quantile(boot.giveup.eff, .025),
                 quantile(boot.giveup.strat,.025)
                 ),
  upper_coef = c(quantile(boot.method.eff, .975),
                 quantile(boot.method.strat,.975),
                 quantile(boot.bf.eff, .975),
                 quantile(boot.bf.strat,.975),
                 quantile(boot.default.eff, .975),
                 quantile(boot.default.strat,.975),
                 quantile(boot.giveup.eff, .975),
                 quantile(boot.giveup.strat,.975)
                 )
)

```

```{r cache = T}
sales.summary
```

## Sports Scenario Analysis

```{r }
## Preparing Data
sports.long <- gather.keep(attobo3, keep = c("...1"), 
                            var.to.gather = c("StratSports", "EffortSports"),
                            key = "attribution",
                            value = "advice"
                            )

sports.long$advice <- as.numeric(factor(sports.long$advice, 
                                levels = c( "Method", "BF","Default", "Give up")
                                ))
sports.long$advice <- sports.long$advice - 1

sports.long$attribution <- factor(sports.long$attribution, 
                                levels = c( "EffortSports", "StratSports"),
                                labels = c("effort", "strategy")
                                )


```

```{r eval = F}

set.seed(100)

df <- data.frame(choices = sports.long$advice, attribution = sports.long$attribution)

df$attribution <- factor(df$attribution )

N <- nrow(df)
nSims <- 5000

boot.method.eff <- c()
boot.method.strat <- c()
boot.bf.eff <- c()
boot.bf.strat <- c()
boot.default.eff <- c()
boot.default.strat <- c()
boot.giveup.eff <- c()
boot.giveup.strat <- c()


for (i in 1:nSims){
  
  df.boot <- df[resample(1:(N), N), ]

  test.boot <- multinom(choices ~ attribution, data = df.boot, trace = F)
  summary(test.boot)
  
  newpred <- data.frame(attribution = c("effort","strategy"))
  pred <- predict(test.boot, newdata = newpred, "prob")
  
  
  boot.method.eff[i] <- pred[1,1]
  boot.method.strat[i] <- pred[2,1]
  boot.bf.eff[i] <- pred[1,2]
  boot.bf.strat[i] <- pred[2,2]
  boot.default.eff[i] <- pred[1,3]
  boot.default.strat[i] <- pred[2,3]
  boot.giveup.eff[i] <- pred[1,4]
  boot.giveup.strat[i] <- pred[2,4]

}

sports.boot <- data.frame(
  boot.method.eff = boot.method.eff,
  boot.method.strat = boot.method.strat,
  boot.bf.eff = boot.bf.eff,
  boot.bf.strat = boot.bf.strat,
  boot.default.eff = boot.default.eff,
  boot.defaule.strat = boot.default.strat,
  boot.giveup.eff = boot.giveup.eff,
  boot.giveup.strat = boot.giveup.strat
)

sports.summary <- data.frame(
  attribution = rep( c("Effort", "Strategy"), 4 ),
  advice = rep( c("Method",  "Bruteforce", "Default", "Give Up"), each = 2 ),
  mean_coef = c(mean(boot.method.eff),mean(boot.method.strat),
                mean(boot.bf.eff),mean(boot.bf.strat),
                mean(boot.default.eff),mean(boot.default.strat),
                mean(boot.giveup.eff),mean(boot.giveup.strat)
                ),
  lower_coef = c(quantile(boot.method.eff, .025),
                 quantile(boot.method.strat,.025),
                 quantile(boot.bf.eff, .025),
                 quantile(boot.bf.strat,.025),
                 quantile(boot.default.eff, .025),
                 quantile(boot.default.strat,.025),
                 quantile(boot.giveup.eff, .025),
                 quantile(boot.giveup.strat,.025)
                 ),
  upper_coef = c(quantile(boot.method.eff, .975),
                 quantile(boot.method.strat,.975),
                 quantile(boot.bf.eff, .975),
                 quantile(boot.bf.strat,.975),
                 quantile(boot.default.eff, .975),
                 quantile(boot.default.strat,.975),
                 quantile(boot.giveup.eff, .975),
                 quantile(boot.giveup.strat,.975)
                 )
)


```

```{r cache = T}
sports.summary
```


## Teamwork Scenario Analysis

```{r }
## Preparing Data
team.long <- gather.keep(attobo3, keep = c("...1"), 
                            var.to.gather = c("StratTeam", "EffortTeam"),
                            key = "attribution",
                            value = "advice"
                            )

team.long$advice <- as.numeric(factor(team.long$advice, 
                                levels = c( "Method", "BF","Default", "Give up")
                                ))
team.long$advice <- team.long$advice - 1

team.long$attribution <- factor(team.long$attribution, 
                                levels = c( "EffortTeam", "StratTeam"),
                                labels = c("effort", "strategy")
                                )


```

```{r eval = F}

set.seed(100)

df <- data.frame(choices = team.long$advice, attribution = team.long$attribution)

df$attribution <- factor(df$attribution )

N <- nrow(df)
nSims <- 5000

boot.method.eff <- c()
boot.method.strat <- c()
boot.bf.eff <- c()
boot.bf.strat <- c()
boot.default.eff <- c()
boot.default.strat <- c()
boot.giveup.eff <- c()
boot.giveup.strat <- c()


for (i in 1:nSims){
  
  df.boot <- df[resample(1:(N), N), ]

  test.boot <- multinom(choices ~ attribution, data = df.boot, trace = F)
  summary(test.boot)
  
  newpred <- data.frame(attribution = c("effort","strategy"))
  pred <- predict(test.boot, newdata = newpred, "prob")
  
  
  boot.method.eff[i] <- pred[1,1]
  boot.method.strat[i] <- pred[2,1]
  boot.bf.eff[i] <- pred[1,2]
  boot.bf.strat[i] <- pred[2,2]
  boot.default.eff[i] <- pred[1,3]
  boot.default.strat[i] <- pred[2,3]
  boot.giveup.eff[i] <- pred[1,4]
  boot.giveup.strat[i] <- pred[2,4]

}

team.boot <- data.frame(
  boot.method.eff = boot.method.eff,
  boot.method.strat = boot.method.strat,
  boot.bf.eff = boot.bf.eff,
  boot.bf.strat = boot.bf.strat,
  boot.default.eff = boot.default.eff,
  boot.defaule.strat = boot.default.strat,
  boot.giveup.eff = boot.giveup.eff,
  boot.giveup.strat = boot.giveup.strat
)

team.summary <- data.frame(
  attribution = rep( c("Effort", "Strategy"), 4 ),
  advice = rep( c("Method",  "Bruteforce", "Default", "Give Up"), each = 2 ),
  mean_coef = c(mean(boot.method.eff),mean(boot.method.strat),
                mean(boot.bf.eff),mean(boot.bf.strat),
                mean(boot.default.eff),mean(boot.default.strat),
                mean(boot.giveup.eff),mean(boot.giveup.strat)
                ),
  lower_coef = c(quantile(boot.method.eff, .025),
                 quantile(boot.method.strat,.025),
                 quantile(boot.bf.eff, .025),
                 quantile(boot.bf.strat,.025),
                 quantile(boot.default.eff, .025),
                 quantile(boot.default.strat,.025),
                 quantile(boot.giveup.eff, .025),
                 quantile(boot.giveup.strat,.025)
                 ),
  upper_coef = c(quantile(boot.method.eff, .975),
                 quantile(boot.method.strat,.975),
                 quantile(boot.bf.eff, .975),
                 quantile(boot.bf.strat,.975),
                 quantile(boot.default.eff, .975),
                 quantile(boot.default.strat,.975),
                 quantile(boot.giveup.eff, .975),
                 quantile(boot.giveup.strat,.975)
                 )
)

```

```{r cache = T}
team.summary
```


## Effect of Context

```{r cache=T}

acad.long$context <- "Academic"
diet.long$context <- "Diet"
parent.long$context <- "Parent"
relation.long$context <- "Relationship"
sales.long$context <- "Sales"
sports.long$context <- "Sports"
team.long$context <- "Teamwork"

context.long <- acad.long %>%
  full_join(diet.long)%>%
  full_join(parent.long)%>%
  full_join(relation.long)%>%
  full_join(sales.long)%>%
  full_join(sports.long)%>%
  full_join(team.long)
```

```{r}

set.seed(100)

df <- data.frame(choices = context.long$advice, attribution = context.long$attribution, context = context.long$context)

df$attribution <- factor(df$attribution )
df$context <- factor(df$context)

context.model <- multinom(choices ~ attribution*context, data = df)

# compute effect size
model.anova <- car::Anova(context.model)
cohen.w <- sqrt(model.anova$`LR Chisq`[1]/(1*nrow(df)))
print(paste("Cohen W:", round(cohen.w,3) ))

library(car)
Anova(context.model)

```


# Graphs


```{r }

load("attobo3.full.summary.RData")
attobo3.full.summary <- attobo3.full.summary[attobo3.full.summary$advice == "Method"| attobo3.full.summary$advice == "Bruteforce", ]
# 
attobo3.full.summary$Attribution <- attobo3.full.summary$attribution
attobo3.full.summary
```



```{r fig.height=12, fig.width=12}

x <- 0
y <- 1.1
attobo3.full.summary$attribution.num <- rep (c(1, y), 14)

attobo3.full.summary$Advice <- factor(attobo3.full.summary$advice, levels = c("Bruteforce", "Method"), 
                                      labels = c("Work Harder", "Methodological"))


attobo3.full.summary.plot <-  ggplot(attobo3.full.summary, aes(x = Attribution, y = mean_coef, fill = Advice)) +
  geom_bar(stat = "identity", position = position_dodge(.9), width = .8) +
  geom_errorbar( aes(ymin=lower_coef, ymax=upper_coef), width=.2,
                 position=position_dodge(.9))+
  ylab("Probability of Advice") + xlab("") + 
  facet_wrap(~context, nrow = 4, scales = c("free"))+
   scale_color_manual(values = c("#D55E00", "#0072B2")) +
    scale_y_continuous(expand = c(0,0), limits = c(0,.9)) +
  theme_bw() +
  theme(text = element_text(size = 28),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

attobo3.full.summary.plot

```
