---
title: "Pre-test Analysis"
output: 
  html_document:
    theme: darkly
    toc: yes
    toc_depth: 3
    toc_float: true
    highlight: tango
    df_print: paged
    fig_caption: false
    code_fold: hide
fontsize: 18pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, warning=FALSE, message=FALSE)
```

```{r echo=FALSE, results='hide', message=F, warning=F}

library(psych)
library(ggplot2)
library(tidyverse)
library(effects)
## Library for the multiple comparisons
library(phia)
## Library to compute the effect sizes
library(sjstats)
library(lsr)
library(lavaan)
library(ggthemes)
library(tibble)
library(car)
library(olsrr)
library(dthelper)

report <- function(x,dp=2){
  m <- round(mean(x, na.rm=T),dp)
  s <- round(sd(x, na.rm=T),dp)
  return(paste0(m, " (", s, ")"))
}
```

```{r loading and wrangling data}
load("attobo.pilot.RData")

# fixing age variable
attobo.pilot$Age[attobo.pilot$Age == 1943] <- 75
attobo.pilot$Age[attobo.pilot$Age == 1984] <- 34
attobo.pilot$Age[attobo.pilot$Age == 1987] <- 31
attobo.pilot$Age[attobo.pilot$Age == 1988] <- 32
attobo.pilot$Age[attobo.pilot$Age == 1992] <- 26

```



# Descriptive Stats

```{r }

summary_stats <- data.frame(
  Attribution = c("Effort", "Strategy", "Aptitude"),
  `Locus (External)` = c(report(attobo.pilot$EffortOut), report(attobo.pilot$StratOut), report(attobo.pilot$AptOut) ),
  `Unstability` = c(report(attobo.pilot$EffortVar), report(attobo.pilot$StratVar), report(attobo.pilot$AptVar) ),
  `Uncontrollability` = c(report(attobo.pilot$EffortUncon), report(attobo.pilot$StratUncon), report(attobo.pilot$AptUncon) )
                  )

summary_stats

attobo.dimensions <- attobo.pilot[, 2:19]

ggplot(data = gather(attobo.dimensions , factor_key = TRUE), aes(x = factor(value))) +
  geom_bar() + 
  facet_wrap(~ key,scales = "free", as.table = TRUE, nrow = 3) + xlab("") + 
  theme_bw()
```


###################################################################

# Attribution Patterns

## Locus of Control (External)

### Hypothesis test

```{r}

t.test(attobo.pilot$EffortOut, attobo.pilot$AptOut, paired = TRUE)

t.test(attobo.pilot$StratOut, attobo.pilot$AptOut,paired = TRUE)

t.test(attobo.pilot$StratOut, attobo.pilot$EffortOut, paired = TRUE)

```

## Stability (higher means more unstable)

### Hypothesis test

```{r}

t.test(attobo.pilot$EffortVar, attobo.pilot$AptVar, paired = TRUE)

t.test(attobo.pilot$StratVar, attobo.pilot$AptVar,paired = TRUE)

t.test(attobo.pilot$StratVar, attobo.pilot$EffortVar, paired = TRUE)

```

## Controllability (higher means more uncontrollable)

### Hypothesis test

```{r}

t.test(attobo.pilot$EffortUncon, attobo.pilot$AptUncon, paired = TRUE)

t.test(attobo.pilot$StratUncon, attobo.pilot$AptUncon,paired = TRUE)

t.test(attobo.pilot$StratUncon, attobo.pilot$EffortUncon, paired = TRUE)

```
