---
title: "Study 2 Analysis"
author: "Dennis Teo"
output:
  html_document:
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: true
    highlight: tango
    df_print: paged
fontsize: 18pt
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message=FALSE)
```

```{r results='hide', eval=TRUE}

library(psych)
library(ggplot2)
library(effects)
## Library for the multiple comparisons
library(phia)
## Library to compute the effect sizes
library(sjstats)
library(lsr)
library(lavaan)
library(ggthemes)
library(tibble)
library(car)
library(olsrr)
library(pwr)
library(car)
library(tidyverse)
library(glm2)
library(betareg)
library(multcomp)
library(dthelper)

select <- dplyr::select

```

```{r eval=TRUE}

library(readr)
attobo2 <- read_csv("attobo2_clean.csv")

```

```{r  results='hide', eval=TRUE}

# failure$scenario <- as.factor(failure$scenario)
attobo2$scenario <- as.factor(attobo2$scenario)
# success$scenario <- as.factor(success$scenario)
attobo2$valence <- as.factor(attobo2$valence)
attobo2$attribution <- as.factor(attobo2$attribution)

attobo2$expectancy <- (attobo2$expectancy - 1)/10
attobo2$expectancy <- ifelse(attobo2$expectancy == 1, .999,
                     ifelse(attobo2$expectancy == 0, .001, attobo2$expectancy) )

attobo2$attribution_effort <- factor(attobo2$attribution, levels = c("Effort", "Strategy", "Aptitude"))
attobo2$attribution_strat <- factor(attobo2$attribution, levels = c( "Strategy","Effort", "Aptitude"))

attobo2$redo.feedback <- ifelse(attobo2$redo == 1 & attobo2$method == 1, 1,0)

attobo2$redo.nofeedback <- ifelse(attobo2$redo == 1 & attobo2$method == 0, 1,0)

attobo2.fail <- attobo2 %>% filter(valence == "Fail")

reverse.logodds <- function(x){
  exp(x)/(1+exp(x))
}
```



# IRR
```{r}

sum(attobo2$method_den == attobo2$method_val)/length(attobo2$method_val)

sum(attobo2$bruteforce_den == attobo2$method_val)/length(attobo2$bruteforce_val)

sum(attobo2$redo_den == attobo2$method_val)/length(attobo2$redo_val)


```



# Descriptive Stats

```{r eval=TRUE}
## Sample Breakdown
group_by(attobo2, attribution) %>%
  summarise(n())
  
##Descriptive stats for the DVs

##method
group_by(attobo2, attribution, valence) %>%
  filter(method == 1) %>%
  summarise(n())

##bruteforce
group_by(attobo2, attribution, valence) %>%
  filter(bruteforce == 1) %>%
  summarise(n())

##redo
group_by(attobo2, attribution, valence) %>%
  filter(redo == 1) %>%
  summarise(n())

##threat
group_by(attobo2, attribution, valence) %>%
  filter(threat == 1) %>%
  summarise(n())

##tangible rewards
group_by(attobo2, attribution, valence) %>%
  filter(tangiblerewards == 1) %>%
  summarise(n())


##Zooming into redo
redo <- attobo2 %>%
  filter(redo == 1)

group_by(attobo2, redo, scenario) %>%
  summarise(n())

##redo with methodological Feedback
group_by(attobo2, redo, scenario) %>%
  filter(method == 1) %>%
  summarise(n())

group_by(attobo2, scenario)%>%
  summarize(method = sum(method == 1&redo==1)/sum(redo==1) )

##expectancy
attobo2 %>%
  group_by(scenario) %>%
  summarise(meanexpectancy = mean(expectancy, na.rm=T),
            sdexpectancy = sd(expectancy, na.rm = T))

noswitch <- attobo2 %>%
  filter(switch == 0)

noswitch %>%
  group_by(scenario) %>%
  count()

noswitch %>%
  group_by(scenario) %>%
  summarise(meanexpectancy = mean(expectancy, na.rm=T),
            sdexpectancy = sd(expectancy, na.rm = T))

####Demographics####

attobo2 %>%
  group_by(gender) %>%
  count()
164/292 #males


mean(attobo2$age)
sd(attobo2$age)

```

```{r eval=TRUE}

attobo2.advice <- attobo2 %>%
  select(method, bruteforce, threat, tangiblerewards,
         switch, expectancy)

attobo2.attribution <- attobo2 %>%
  select(aptout, aptvar, aptuncon, 
         effortout, effortvar, effortuncon,
         stratout, stratvar, stratuncon,
         luckout, luckvar, luckuncon,
         taskout, taskvar, taskuncon,
         moodout, moodvar, mooduncon)

attobo2.others <- attobo2 %>%
  select(gender, age, education, sms,
         smo, so, race)

ggplot(data = gather(attobo2.advice, factor_key = TRUE), aes(x = factor(value))) +
  geom_bar() + 
  facet_wrap(~ key,scales = "free", as.table = TRUE, nrow = 3) + xlab("") + 
  theme_bw()

ggplot(data = gather(attobo2.attribution, factor_key = TRUE), aes(x = factor(value))) +
  geom_bar() + 
  facet_wrap(~ key,scales = "free", as.table = TRUE, nrow = 3) + xlab("") + 
  theme_bw()

ggplot(data = gather(attobo2.others, factor_key = TRUE), aes(x = factor(value))) +
  geom_bar() + 
  facet_wrap(~ key,scales = "free", as.table = TRUE, nrow = 3) + xlab("") + 
  theme_bw()

```


# Main Analysis

## Methodological Advice
```{r}
method.freq <- glm2(method ~ attribution_strat*valence, data = attobo2, family = binomial(link = "logit"))

summary(method.freq)
confint(method.freq)
Anova(method.freq)

method.coefs <- summary(method.freq)$coefficients

## Failure

# strategy
reverse.logodds(method.coefs[1, "Estimate"])
reverse.logodds(confint(method.freq)[1,])

# effort
reverse.logodds(method.coefs[1, "Estimate"] + method.coefs[2, "Estimate"])
reverse.logodds(method.coefs[1, "Estimate"] + confint(method.freq)[2,])

# aptitude
reverse.logodds(method.coefs[1, "Estimate"] + method.coefs[3, "Estimate"])
reverse.logodds(method.coefs[1, "Estimate"] + confint(method.freq)[3,])


## Success

# strategy
reverse.logodds(method.coefs[1, "Estimate"]+method.coefs[4, "Estimate"])
reverse.logodds(confint(method.freq)[1,]+method.coefs[4, "Estimate"])

# effort
reverse.logodds(method.coefs[1, "Estimate"] + method.coefs[2, "Estimate"]+method.coefs[4, "Estimate"])
reverse.logodds(method.coefs[1, "Estimate"]+method.coefs[4, "Estimate"] + confint(method.freq)[2,])

# aptitude
reverse.logodds(method.coefs[1, "Estimate"] + method.coefs[3, "Estimate"]+method.coefs[4, "Estimate"])
reverse.logodds(method.coefs[1, "Estimate"]+method.coefs[4, "Estimate"] + confint(method.freq)[3,])

coef.summary <- data.frame(
  advice = rep("Methodological",3),
  attribution = c("Strategy", "Effort","Aptitude"),
  mean = c(reverse.logodds(method.coefs[1, "Estimate"]), reverse.logodds(method.coefs[1, "Estimate"] + method.coefs[2, "Estimate"]), reverse.logodds(method.coefs[1, "Estimate"] + method.coefs[3, "Estimate"])),
  lower = c(reverse.logodds(confint(method.freq)[1,])[1], reverse.logodds(method.coefs[1, "Estimate"] + confint(method.freq)[2,])[1], reverse.logodds(method.coefs[1, "Estimate"] + confint(method.freq)[3,])[1]),
  upper = c(reverse.logodds(confint(method.freq)[1,])[2], reverse.logodds(method.coefs[1, "Estimate"] + confint(method.freq)[2,])[2], reverse.logodds(method.coefs[1, "Estimate"] + confint(method.freq)[3,])[2])
)

```


## Work Harder Advice

```{r}

bruteforce.freq <- glm2(bruteforce ~ attribution_effort*valence, data = attobo2, family = binomial(link = "logit"))


summary(bruteforce.freq)
confint(bruteforce.freq)
Anova(bruteforce.freq)

bruteforce.coefs <- summary(bruteforce.freq)$coefficients

## Failure

# effort
reverse.logodds(bruteforce.coefs[1, "Estimate"])
reverse.logodds(confint(bruteforce.freq)[1,])

# strategy
reverse.logodds(bruteforce.coefs[1, "Estimate"] + bruteforce.coefs[2, "Estimate"])
reverse.logodds(bruteforce.coefs[1, "Estimate"] + confint(bruteforce.freq)[2,])

# aptitude
reverse.logodds(bruteforce.coefs[1, "Estimate"] + bruteforce.coefs[3, "Estimate"])
reverse.logodds(bruteforce.coefs[1, "Estimate"] + confint(bruteforce.freq)[3,])


## Success

# effort
reverse.logodds(bruteforce.coefs[1, "Estimate"]+bruteforce.coefs[4, "Estimate"])
reverse.logodds(confint(bruteforce.freq)[1,]+bruteforce.coefs[4, "Estimate"])

# strategy
reverse.logodds(bruteforce.coefs[1, "Estimate"] + bruteforce.coefs[2, "Estimate"]+bruteforce.coefs[4, "Estimate"])
reverse.logodds(bruteforce.coefs[1, "Estimate"]+bruteforce.coefs[4, "Estimate"] + confint(bruteforce.freq)[2,])

# aptitude
reverse.logodds(bruteforce.coefs[1, "Estimate"] + bruteforce.coefs[3, "Estimate"]+bruteforce.coefs[4, "Estimate"])
reverse.logodds(bruteforce.coefs[1, "Estimate"]+bruteforce.coefs[4, "Estimate"] + confint(bruteforce.freq)[3,])

coef.summary <- rbind(coef.summary, data.frame(
  advice = rep("Work Harder",3),
  attribution = c("Effort","Strategy","Aptitude"),
  mean = c(reverse.logodds(bruteforce.coefs[1, "Estimate"]), reverse.logodds(bruteforce.coefs[1, "Estimate"] + bruteforce.coefs[2, "Estimate"]), reverse.logodds(bruteforce.coefs[1, "Estimate"] + bruteforce.coefs[3, "Estimate"])),
  lower = c(reverse.logodds(confint(bruteforce.freq)[1,])[1], reverse.logodds(bruteforce.coefs[1, "Estimate"] + confint(bruteforce.freq)[2,])[1], reverse.logodds(bruteforce.coefs[1, "Estimate"] + confint(bruteforce.freq)[3,])[1]),
  upper = c(reverse.logodds(confint(bruteforce.freq)[1,])[2], reverse.logodds(bruteforce.coefs[1, "Estimate"] + confint(bruteforce.freq)[2,])[2], reverse.logodds(bruteforce.coefs[1, "Estimate"] + confint(bruteforce.freq)[3,])[2])
))

```


## Try Again Advice

```{r}
redo.freq <- glm2(redo ~ attribution_effort*valence, data = attobo2, family = binomial(link = "logit"))

redo.freq.alt <- glm2(redo ~ attribution*valence, data = attobo2, family = binomial(link = "logit"))

summary(redo.freq)
confint(redo.freq)
Anova(redo.freq)

summary(redo.freq.alt)

redo.coefs <- summary(redo.freq)$coefficients

## Failure

# effort
reverse.logodds(redo.coefs[1, "Estimate"])
reverse.logodds(confint(redo.freq)[1,])

# strategy
reverse.logodds(redo.coefs[1, "Estimate"] + redo.coefs[2, "Estimate"])
reverse.logodds(redo.coefs[1, "Estimate"] + confint(redo.freq)[2,])

# aptitude
reverse.logodds(redo.coefs[1, "Estimate"] + redo.coefs[3, "Estimate"])
reverse.logodds(redo.coefs[1, "Estimate"] + confint(redo.freq)[3,])


## Success

# effort
reverse.logodds(redo.coefs[1, "Estimate"]+redo.coefs[4, "Estimate"])
reverse.logodds(confint(redo.freq)[1,]+redo.coefs[4, "Estimate"])

# strategy
reverse.logodds(redo.coefs[1, "Estimate"] + redo.coefs[2, "Estimate"]+redo.coefs[4, "Estimate"])
reverse.logodds(redo.coefs[1, "Estimate"]+redo.coefs[4, "Estimate"] + confint(redo.freq)[2,])

# aptitude
reverse.logodds(redo.coefs[1, "Estimate"] + redo.coefs[3, "Estimate"]+redo.coefs[4, "Estimate"])
reverse.logodds(redo.coefs[1, "Estimate"]+redo.coefs[4, "Estimate"] + confint(redo.freq)[3,])

coef.summary <- rbind(coef.summary, data.frame(
  advice = rep("Try Again",3),
  attribution = c("Effort","Strategy","Aptitude"),
  mean = c(reverse.logodds(redo.coefs[1, "Estimate"]), reverse.logodds(redo.coefs[1, "Estimate"] + redo.coefs[2, "Estimate"]), reverse.logodds(redo.coefs[1, "Estimate"] + redo.coefs[3, "Estimate"])),
  lower = c(reverse.logodds(confint(redo.freq)[1,])[1], reverse.logodds(redo.coefs[1, "Estimate"] + confint(redo.freq)[2,])[1], reverse.logodds(redo.coefs[1, "Estimate"] + confint(redo.freq)[3,])[1]),
  upper = c(reverse.logodds(confint(redo.freq)[1,])[2], reverse.logodds(redo.coefs[1, "Estimate"] + confint(redo.freq)[2,])[2], reverse.logodds(redo.coefs[1, "Estimate"] + confint(redo.freq)[3,])[2])
))
```

## Expectancy

```{r}
expectancy.freq <- betareg(expectancy ~ attribution*valence, data = attobo2, link = "logit" )

expectancy.coefs <- summary(expectancy.freq)$coefficients$mean

## Failure

# aptitude
reverse.logodds(expectancy.coefs[1, "Estimate"])
reverse.logodds(confint(expectancy.freq)[1,])

# effort
reverse.logodds(expectancy.coefs[1, "Estimate"] + expectancy.coefs[2, "Estimate"])
reverse.logodds(expectancy.coefs[1, "Estimate"] + confint(expectancy.freq)[2,])

# strategy
reverse.logodds(expectancy.coefs[1, "Estimate"] + expectancy.coefs[3, "Estimate"])
reverse.logodds(expectancy.coefs[1, "Estimate"] + confint(expectancy.freq)[3,])


## Success

# aptitude
reverse.logodds(expectancy.coefs[1, "Estimate"]+expectancy.coefs[4, "Estimate"])
reverse.logodds(confint(expectancy.freq)[1,]+expectancy.coefs[4, "Estimate"])

# effort
reverse.logodds(expectancy.coefs[1, "Estimate"] + expectancy.coefs[2, "Estimate"]+expectancy.coefs[4, "Estimate"]+ expectancy.coefs[5, "Estimate"])
reverse.logodds(expectancy.coefs[1, "Estimate"]+expectancy.coefs[4, "Estimate"] + confint(expectancy.freq)[2,]+ expectancy.coefs[5, "Estimate"])

# strategy
reverse.logodds(expectancy.coefs[1, "Estimate"] + expectancy.coefs[3, "Estimate"]+expectancy.coefs[4, "Estimate"]+ expectancy.coefs[6, "Estimate"])
reverse.logodds(expectancy.coefs[1, "Estimate"]+expectancy.coefs[4, "Estimate"] + confint(expectancy.freq)[3,]+ expectancy.coefs[6, "Estimate"])

```



```{r}




summary(betareg(expectancy ~ attribution*valence, data = attobo2, link = "logit" ))

Anova(glm2(method ~ attribution_strat*valence, data = attobo2, family = binomial(link = "logit")))

Anova(glm2(bruteforce ~ attribution_effort*valence, data = attobo2, family = binomial(link = "logit")))

Anova(glm2(redo ~ attribution_effort*valence, data = attobo2, family = binomial(link = "logit")))

Anova(betareg(expectancy ~ attribution*valence, data = attobo2, link = "logit" ))

```


# Graphs

```{r}


coef.summary$Advice <- factor(coef.summary$advice, levels = c("Work Harder", "Methodological","Try Again"))

coef.summary$Attribution <- factor(coef.summary$attribution, levels = c("Effort", "Strategy", "Aptitude"))


```

```{r eval = F}

attobo2.advice.full.plot <-  ggplot(coef.summary, aes(x = Attribution, y = mean, shape = Advice)) + 
  geom_errorbar( aes(ymin=lower, ymax=upper), width=.2,
                 position=position_dodge(.4)) +
  geom_point(aes(col = Advice), position=position_dodge(.4), size = 4) +
  scale_color_manual(values = c("#D55E00", "#0072B2", "#E69F00")) +
  scale_shape_manual(values = c(16,17,18))+
  ylab("Probability of Advice") + xlab("") + 
  facet_wrap(~`Outcome Valence`)+
  theme_bw() +
  theme(text = element_text(size = 16),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())


attobo2.advice.full.plot

```

```{r}

attobo2.advice.full.plot <-  ggplot(coef.summary, aes(x = Attribution, y = mean, shape = Advice)) + 
  geom_errorbar( aes(ymin=lower, ymax=upper), width=.2,
                 position=position_dodge(.4)) +
  geom_point(aes(col = Advice), position=position_dodge(.4), size = 4) +
  scale_color_manual(values = c("#D55E00", "#0072B2", "#E69F00")) +
  scale_shape_manual(values = c(16,17,18))+
  ylab("Probability of Advice") + xlab("") + 
  theme_bw() +
  theme(text = element_text(size = 16),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())


attobo2.advice.full.plot

```




